export const sheet_master = {
  TELEPHONE: '電話',
  WORD_CHAIN: '接龍',
  PAYMENT_STATUS: '通知付款狀態',
  NAME: '名字',
  WECHAT_ID: '微信ID(可以找到人)',
  REMARKS: '备注',
  ORDER_TIME: '下单时间',
  CATEGORY: '類別',
  PRODUCT_NAME: '商品名称',
  SPECIFICATIONS: '规格',
  QUANTITY: '数量',
  PRICE: '商品总金额',
  SCAN_OUT: 'ScanOut',
  SHIPPING_COST: '运费',
  TOTAL_ORDER_AMOUNT: '订单总金额',
  PAID_STATUS: '付款情況',
  PACKING_STATUS: '裝箱情況',
  SHIPPING_STATUS: '發貨狀態',
  ENGLISH_NAME: '收件人名字(英文)',
  PHONE: '电话',
  ADDRESS: '地址(自提填123)',
  EMAIL: '郵箱 (發tracking)',
  ORDER_ID: 'OrderId',
  FULFILLABLE: 'Fulfillable',
}

export const sheet_products = {
  BRAND: 'Brand',
  PRODUCT_NAME: '商品名称',
  SPECIFICATION: '规格',
  INVENTORY: 'Inventory',
  PICTURE: 'Picture',
  BARCODE: 'Barcode'
};

export const sheet_rawqjl = {
  ORDER_ID: "订单号",
  ORDER_SEQUENCE: "下单序号",
  CHAIN_NUMBER: "接龙号",
  LEADER_CHAIN_NUMBER: "帮卖团长接龙号",
  MERCHANT: "所属商家",
  WECHAT_NAME: "微信名称",
  USER_NOTES: "用户备注",
  ORDER_TIME: "下单时间",
  SHIPPING_TIMELINESS: "发货时效",
  INITIATOR_NOTES: "发起人备注",
  PRODUCT_CODE: "商品编码",
  PRODUCT_NAME: "商品名称",
  ORIGINAL_PRODUCT_NAME: "原商品名称",
  SPECIFICATION: "规格",
  PRODUCT_CATEGORY: "商品分类",
  QUANTITY: "数量",
  UNIT_WHOLESALE_PRICE: "商品金额(批发价单价)",
  TOTAL_PRODUCT_AMOUNT: "商品总金额",
  COST_PRICE: "成本价",
  SHIPPING_FEE: "运费",
  REFUNDED_SHIPPING_FEE: "已退运费",
  DISCOUNT_AMOUNT: "优惠金额",
  ORDER_TOTAL_WHOLESALE: "订单总金额(批发价)",
  ORDER_TOTAL: "订单总金额",
  ORDER_REFUNDED_AMOUNT: "订单已退款",
  COMMISSION_PAID: "已发放佣金",
  ORDER_STATUS: "订单状态",
  IMPORT_STATUS: "导单状态",
  LATEST_SHIPPING_TIME: "最新发货时间",
  AFTER_SALES_STATUS: "售后状态",
  REFUND_STATUS: "退款状态",
  CHECK_IN_STATUS: "签到状态",
  PAYMENT_STATUS: "支付状态",
  GROUP_PURCHASE_STATUS: "拼团状态",
  PROMOTER: "所属推广员",
  GROUP_LEADER: "所属团长",
  ASSISTANT_GROUP_LEADER: "所属帮卖团长",
  PICKUP_POINT: "所属提货点",
  ROUTE: "所属路线",
  RECIPIENT_NAME: "收货人",
  CONTACT_PHONE: "联系电话",
  PROVINCE: "省",
  CITY: "市",
  DISTRICT: "区",
  SHIPPING_ADDRESS: "收货地址",
  AFTER_SALES_TYPE: "售后类型",
  AFTER_SALES_STATUS_NEW: "售后状态(新)",
  AFTER_SALES_ADDRESS: "售后地址",
  RETURN_COURIER: "退换货快递公司",
  EXCHANGE_PRODUCT_INFO: "换货商品信息",
  RETURN_TRACKING_NUMBER: "退换货快递单号",
  RETURN_DELIVERY_STATUS: "退换快递签收状态",
  RECIPIENT_NAME_EN: "收件人名字(英文)",
  ALT_PHONE: "电话",
  ALT_ADDRESS: "地址(自提填123)",
  WECHAT_ID: "微信ID(可以找到人)",
  EMAIL: "邮箱(收快递单号)"
};


export const sheet_rawpt = {
  ORDER_ID: '订单号',
  ORDER_TIME: '下单时间',
  CUSTOMER_NICKNAME: '顾客昵称',
  ORDER_NOTES: '订单备注',
  PUBLIC_TAG: '公开标记',
  PRIVATE_TAG: '隐私标记',
  PRODUCT_CATEGORY: '商品分类',
  PRODUCT_CODE: '商品编码',
  PRODUCT_NAME: '商品名称',
  PRODUCT_SPEC: '商品规格',
  PRODUCT_QUANTITY: '商品数量',
  PRODUCT_UNIT_PRICE: '商品单价',
  PRODUCT_UNIT: '商品单位',
  PRODUCT_STATUS: '商品状态',
  PRODUCT_TRACKING_NUMBER: '商品运单号',
  PRODUCT_TYPE_COUNT: '商品种类数',
  PRODUCT_TOTAL_PRICE: '商品总价',
  ORDER_SHIPPING_FEE: '订单运费',
  ORDER_DISCOUNT: '订单优惠',
  MEMBER_DISCOUNT: '会员折扣',
  COUPON: '优惠券',
  ORDER_AMOUNT: '订单金额',
  ORDER_STATUS: '订单状态',
  DELIVERY_METHOD: '配送方式',
  PICKUP_POINT: '自提点',
  PICKUP_POINT_NOTES: '自提点说明',
  RECIPIENT_NAME: '收货人',
  RECIPIENT_PHONE: '收货人电话',
  DELIVERY_ADDRESS: '地址'
};

export const sheet_user = {
  PHONE: '電話',
  WECHAT_ID: '微信ID(可以找到人)',
  NAME: '名字',
  RECIPIENT_NAME_EN: '收件人名字(英文)',
  ADDRESS: '地址(自提填123)',
  EMAIL: 'Email',
};

export const sheet_orders = {
  ID: 'ID',
  PHONE: '電話',
  WORD_CHAIN: '接龍',
  PAYMENT_STATUS: '通知付款狀態',
  REMARKS: '备注',
  ORDER_TIME: '下单时间',
  SHIPPING_COST: '运费',
  TOTAL_ORDER_AMOUNT: '订单总金额',
  PAID_STATUS: '付款情況',
  PACKING_STATUS: '裝箱情況',
  SHIPPING_STATUS: '發貨狀態',
  ADDRESS: '地址(自提填123)',
  SHIPPING1: 'Shipping1',
  SHIPPING2: 'Shipping2',
  FULFILLABLE: 'Fulfillable'
}

export const sheet_orderItems = {
  ID: 'ID',
  BRAND: 'Brand',
  PRODUCT_NAME: '商品名称',
  SPECIFICATION: '规格',
  QUANTITY: '数量',
  TOTAL_PRODUCT_AMOUNT: '商品总金额',
  ORDER_ID: 'OrderId',
  PACKED: 'Packed',
  DELIVERED: 'Delivered',
  FULFILLABLE: 'Fulfillable'
}